### ISSUE TITLE
What is the use of static folder in reality?

### ISSUE THREAD

**Issue by mannok** [electron-userland/electron-webpack#259]
If I am developing a website, static folder provide me a way to serve the app with dynamic resources after compiled the web app. All I need is to modify the compiled static folder content.

However, with electron-vue, all I saw is it help me to bundle all the project into a archive named app.asar. The static folder in located inside with C:\\Projects\\User1\\NodeJS\\my-app\\build\\win-unpacked\\resources\\app.asar\\dist\\electron\\static. Since it is a archive, I lost the ability to change the static folder's content dynamically. So what is the use of static folder?

Thanks in advance.

**Comment by loopmode** [comment]
@mannok "static" refers to "static assets" or: "files that do not need transpiling, compiling or any other processing"; basically, I understand it as "non-code assets" that just need to be "available".
You can use the static folder for images, markdown files, text, json etc.
Those files will not be bundled by webpack, but they will still be included in the final asar archive. In some cases, this might help your dev-server performance, e.g. if you had a really large number of such files, or really large ones, and you put then into static, they would not be part of webpack's dependency tree and they wouldn't slow it down either.

Some node APIs (like the `fs` module) need a full path to a file, and using the static folder together with the global `__static` variable allows you to do that. Sometimes you might have to use that. (This is also explained [in the docs](https://webpack.electron.build/using-static-assets)

On the other hand, if you have a json file in `src/`, you can just import or require it using a relative path. But if you have it in `static/`, you can not do that - then you must use `fs.readFile` to get it's contents and parse  yourself.

**Comment by mannok** [comment]
@loopmode thank you so much for your reply. I have been waited for so long. 

However, I still have some question. AFAIK file in static folder will be compressed into asar archive in production build. Then how can I access it by using just a normal path as how I access a file as usual?

**Comment by loopmode** [comment]
@mannok The `__static` variable gets replaced with the actual path to the files inside the asar at runtime.
So, effectively, you write `fs.readFile(__static + 'file.txt')`, and at runtime, that becomes e.g. `fs.readFile('c:/path-to-the-installation-dir/path-to-the-asar/static/file.txt')`.
Don't take it too literally, haven't seen a real path, not sure whether it uses the asar as a path fragment. (Would be interesting to build a test app and see what final paths look like)

But basically that's what happens - at runtime, your code gets an absolute path to the static file inside the asar, wherever it may be located.

Coming back to your last question: This means you can't access such static file by using a normal path as usual. 
That's because you can't know where the app and the asar are located after installation. Keep in mind that this way, you don't have to care about development vs production environment - you just use `__static` and you get different paths in development and production apps.

**Comment by loopmode** [comment]
Just for information/inspiration, maybe you have a similar use case.

In the app I created with `electron-webpack`, I had to load many many 3D models. My first idea was to put them into static folder and use from there.

In the end, I decided against it, for two reasons:
1) I had about 1GB of such files, build process took forever, installer was gigantic etc. I had to increase memory just to make the build work.
2) If I wanted to change some of those 3D models, I would have to rebuild the entire app, install it again. Or learn the auto-updater features - for very heavy updates. Too much overhead.

That's when I realized that `__static` was simply not the right feature for my use case. 
Instead, for this functionality, I implemented a config system where I could optionally specify an `assetsPath`, and I put my static files there.
When the app got deployed (on 6 computers in an exhibition), I created a config file on each machine and pointed assetsPath to `c:/models`. Then I used `fs` to load my files from there, then gave them to a library for parsing (three.js in that case)
This way, when customer wanted updated artwork, I was able to replace just the 3D models without touching the app itself.

**Comment by mannok** [comment]
@loopmode Sorry for slow reply. I am currently in a trip.

I understand what you suffer from in the first place. And I know that how you can solve it by specifying the local pc path instead of putting the file in static file.

But I still don't understand how static folder give me  benefit me in production mode. All assets in static folder will be archived in asar file. We can no longer access them in order to use them.

**Comment by loopmode** [comment]
Well it's not about you using them, bit your application. Depending on the use case, you will need some files or data in your app that is not code. 
That's not hypothetical, it's a real-world software situation.
And if you are in that situation - what else would you prefer than have those files and data bundled into your app..?
it's about static files, the opposite of dynamic. It's not about exchanging those files, it's about needing them in the program you wrote.

**Comment by loopmode** [comment]
Closing this issue as it isn't a technical issue or constructive. There are various use cases for this feature, and I think we did cover the topic properly in this discussion.
