### ISSUE TITLE
Webpack configuration not working for Typescript/React with @material-ui 

### ISSUE THREAD

**Issue by esakal** [electron-userland/electron-webpack#314]
Hello,
Thank you for this extremely cool devop library!
* **Version**: 2.7.4
* **Target**:  electron 5.0.9

## Reproducible repo
see this [reproducible repo](https://github.com/homefunds/homefunds/tree/devop/packages/%40homefunds/hooks-issue-app).
1. run `npm i`
2. run `npm run dev`

## What I did
1. Created a new repo based on the [quick-start](https://webpack.electron.build/#quick-start).
2. Added the react addon and typescript support
3. Replaced index.js file with relevant `index.tsx` file
```
// NOT WORKING
// export function Test() {
// 	const [value] = useState('Hello');
// 	return <StylesProvider injectFirst={true}><div>{value}</div></StylesProvider>;
// }

// WORKING
export function Test() {
	const [value] = useState('Hello');
	return <div>{value}</div>;
}
```

## Expected
Electron app opens with the text `Hello`
![image](https://user-images.githubusercontent.com/4751797/62769852-81ffbd00-baa2-11e9-85c1-92293e5644e5.png)

## Actual
I'm getting the following message:
![image](https://user-images.githubusercontent.com/4751797/62769650-13bafa80-baa2-11e9-86ea-2023286a3372.png)

## It works without material-ui StylesProvider
Hooks seems to work for regular hooks this is why I suspect it relates to `electron-webpack`  webpack configuration.
```
export function Test() {
	const [value] = useState('Hello');
	return <div>{value}</div>;
}
```

What can I do? Thanks!

**Comment by loopmode** [comment]
Just a shot in the dark, but try whitelisting material-ui.
Search docs for whiteListedModules.
Normally, all packages are treated as webpack externals in electron-webpack, unless you whitelist them.

The issue can happen, if more than one react-dom module is loaded, which could be the case when it's treated as external.

If it doesn't help, we can look onwards.

**Comment by esakal** [comment]
@loopmode Amazing, great advice!  whitelisting `material-ui` worked. I must admit that I don't understand why to external all dependencies **for** `electron-renderer` target. 

> Since webpack is set to target the electron environment, all modules are treated as externals. Unfortunately...

It make sense to external everything for the `main` process as this should transpile to regular node module with dependencies resolved at runtime from `node_modules`. Regarding the `renderer` process as it runs in electron browser, everything should be bundled into the application javascript files. This is what I was thinking anyway. 

What am I missing?

Thanks a lot I spend so many hours trying to figure this one out.  👍

**Comment by loopmode** [comment]
Maybe you're missing nothing! Maybe you just pointed out a design flaw.

@develar what do you think about that reasoning. I lack deep enough knowledge, but seems to me @esakal has a good point there about renderer bundling..

**Comment by loopmode** [comment]
@esakal 

```
Thanks a lot! I spent so many hours trying to figure this one out. 👍
```

Only do that as long as it's fun and interesting. When it becomes frustrating, just post an issue here. It's a small but benevolent community, and chances are someone spent the sleepless nights already. :)

**Comment by esakal** [comment]
@loopmode thanks for your kindness, tackling devop issues can be sometime frustrating.  

Although we need to bundle 99% of the dependencies there are few that should be keep external, an example can be `electron`. Taken from webpack target documentation about [`electron-renderer`](https://webpack.js.org/configuration/target/#string):

> ... for browser environments and NodeTargetPlugin and ExternalsPlugin for CommonJS and Electron built-in modules ....

Using the super cool support `electron-webpack` provides to customize webpack renderer config, doing the following...

```
module.exports = function(config) {
  const newConfig = {
    ...config,
    target: 'electron-renderer',
    externals: [],
    resolve: {
      ...config.resolve,
      alias: {
        ...config.resolve.alias,
      }
    }
  };
  return newConfig;
}
```
...Produced a bundle file with all the dependencies beside `electron` which was marked as external and I think is the desired result.
```
/*!***************************!*\
  !*** external "electron" ***!
  \***************************/
/*! no static exports found */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,a){e.exports=require("electron")}});
//# sourceMappingURL=renderer.js.map
```

The thing is that removing `target: 'electron-renderer'` and keeping `externals: []`  from the configuration above produced the same result and `electron` was still handled as external somehow... not sure who in the chain enforced this behavior.

Anyway just wanted to elaborate about the `electron` dependency which should be external  together with few other built-in modules.

**Comment by walleXD** [comment]
I'm having a similar issue with `connected-react-router` but adding it to `whiteListedModules` doesn't solve the problem. Any idea what's going on @loopmode ?

**Comment by loopmode** [comment]
@walleXD I don't know that one, but did you try whitelisting `react-router` or `react-router-dom` instead?

**Comment by esakal** [comment]
@walleXD did you try overriding the externals and adding target? Something like
```
const path = require('path');
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

module.exports = function(config) {
  const newConfig = {
    ...config,
    devServer: {
      ...config.devServer,
      historyApiFallback: true
    },
    target: 'electron-renderer',
    externals: [],
    resolve: {
      ...config.resolve,
      alias: {
        ...config.resolve.alias,
        "@app/shared": path.resolve(__dirname, 'src/renderer/shared')
      }
    },
    plugins: [
      ...config.plugins,
      new MomentLocalesPlugin()
    ]
  };
  return newConfig;
}
```
Without the moment and the resolved part ( i copied it from my code)

Didnt try to publish it yet. but it seems to work in dev

**Comment by loopmode** [comment]
The target should already be already set, but simply overriding the externals with empty array seems to be a good idea.

**Comment by walleXD** [comment]
weirdly enough, for me the solution was whitelisting `react-redux`. Otherwise hooks seem to fail from external libraries  🙏🏼

**Comment by mattblackdev** [comment]
Yeah... check this out: https://github.com/facebook/react/issues/13991#issuecomment-521903787

```
// webpack.renderer.js
module.exports = {
    externals: [
        "react",
        "react-dom"
    ],
};
```

**Comment by pixelass** [comment]
I had the same issue with `react-beautiful-dnd@11.x.x`

Adding `react-beautiful-dnd` to whiteListedModules OR `react` to webpack.renderer.additions.js solved this issue for me. I'm not sure which option is better but for now I'm running with the whiteListedModules option.

**Comment by ccforeverd** [comment]
@mattblackdev resolved, thank you! i met this problem in electron too. thank you so much, save me a lot time~

**Comment by loopmode** [comment]
Closing, as whitelisting modules seems to be the proper solution here.

**Comment by esakal** [comment]
@loopmode I'm not sure the solution mentioned is sufficient for the renderer part. The default behavior should be to enable *all modules* except `electron` which in my opinion is added by electron itself. All the other modules must be bundled into the renderer. 

this is what I did to make sure everything is bundled and nothing is considered as `external`. I didn't check if it works without bundling `electron` but I think it should be considered as well.

```
module.exports = function(config) {
  const newConfig = {
    ...config,
    devServer: {
      ...config.devServer,
      historyApiFallback: true
    },
    target: 'electron-renderer',
    externals: [],
  };
  return newConfig;
}
```

**Comment by mattblackdev** [comment]
@esakal Are you saying `react` and `react-dom` should not be in the externals? Can you help me understand what's going on here: https://github.com/facebook/react/issues/13991#issuecomment-521903787?

**Comment by loopmode** [comment]
@esakal I see your point. Luckily, I just started a new electron-webpack project and have some capacity there, so I'll try that out for a while. I wonder about performance implications in largish apps.
Also I look forward to try out webpack-bundle-analyzer for literally a clear picture of how things are.
